### ISSUE TITLE
plustic 9.0.0 crash on start up issue

### ISSUE THREAD

**Issue by touhouzun** [queengooborg/PlusTiC-Reforged#1]
plustic-9.0.0
1.12.2-forge1.12.2-14.23.5.2860
https://gist.github.com/touhouzun/7bfcb86efd6d1ca385727d92b0f35a47
https://gist.github.com/touhouzun/1bee4d379095401989f90c03c81d7ead
Also plustic fails to generate a config (empty)

**Comment by Nightreaver** [comment]
same here, would love to see a fix

**Comment by queengooborg** [comment]
Apparently this was an issue with attempting to upgrade the Forge version for development, as that particular bit of code was otherwise untouched.  Just tested out a new version on Forge 14.23.5.2859 and confirmed it's working now.  I've uploaded version 9.0.1 to CurseForge, which should be available soon!

**Comment by Nightreaver** [comment]
hm... still not there

**Comment by queengooborg** [comment]
CurseForge is still reviewing the mod, so the update will not be available until it has been reviewed.  It should appear within 24 hours!
